-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS gamestore.game
(
    id serial NOT NULL,
    title character varying(50) NOT NULL,
    description character varying(2000) NOT NULL,
    date_release date NOT NULL,
    price real NOT NULL,
    system_required character varying(500) NOT NULL,
    publisher_id integer NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (title),
	CHECK (price >= 0)
);

CREATE TABLE IF NOT EXISTS gamestore.publisher
(
    id serial NOT NULL,
    name character varying(30) NOT NULL,
    country_id integer NOT NULL,
    PRIMARY KEY (id),
	UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS gamestore.country
(
    id serial NOT NULL,
    name character varying(30) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS gamestore.developer
(
    id serial NOT NULL,
    name character varying(30) NOT NULL,
    country_id integer NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS gamestore.game_developer
(
    game_id integer NOT NULL,
    developer_id integer NOT NULL,
	UNIQUE (game_id, developer_id)
);

CREATE TABLE IF NOT EXISTS gamestore.game_version
(
    id serial NOT NULL,
    game_id integer NOT NULL,
    date_release date NOT NULL,
    description text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS gamestore.genre
(
    id serial NOT NULL,
    name character varying(30) NOT NULL,
    PRIMARY KEY (id),
	UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS gamestore.game_genre
(
    game_id integer NOT NULL,
    genre_id integer NOT NULL,
	UNIQUE(game_id, genre_id)
);

CREATE TABLE IF NOT EXISTS gamestore."user"
(
    id serial NOT NULL,
    login character varying(30) NOT NULL,
    wallet real NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
	UNIQUE (login),
	CHECK (wallet >= 0)
);

CREATE TABLE IF NOT EXISTS gamestore.game_user
(
    game_id integer NOT NULL,
    user_id integer NOT NULL,
    date_purchase date NOT NULL,
    price real NOT NULL,
	UNIQUE(game_id, user_id)
);

ALTER TABLE IF EXISTS gamestore.game
    ADD FOREIGN KEY (publisher_id)
    REFERENCES gamestore.publisher (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS gamestore.publisher
    ADD FOREIGN KEY (country_id)
    REFERENCES gamestore.country (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS gamestore.game_developer
    ADD FOREIGN KEY (game_id)
    REFERENCES gamestore.game (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS gamestore.game_developer
    ADD FOREIGN KEY (developer_id)
    REFERENCES gamestore.developer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS gamestore.game_version
    ADD FOREIGN KEY (game_id)
    REFERENCES gamestore.game (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS gamestore.game_genre
    ADD FOREIGN KEY (game_id)
    REFERENCES gamestore.game (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS gamestore.game_genre
    ADD FOREIGN KEY (genre_id)
    REFERENCES gamestore.genre (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS gamestore.game_user
    ADD FOREIGN KEY (game_id)
    REFERENCES gamestore.game (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS gamestore.game_user
    ADD FOREIGN KEY (user_id)
    REFERENCES gamestore."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;